services:
  postgres:
    image: postgres:16-alpine
    container_name: devsecops-postgres
    environment:
      POSTGRES_USER: devsecops
      POSTGRES_PASSWORD: devsecops
      POSTGRES_DB: devsecops
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsecops"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - devsecops

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: devsecops-api
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/devsecops
      DB_USER: devsecops
      DB_PASSWORD: devsecops
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:8081:8080"
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - devsecops

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: devsecops-worker
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/devsecops
      DB_USER: devsecops
      DB_PASSWORD: devsecops
    depends_on:
      postgres:
        condition: service_healthy
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - devsecops

networks:
  devsecops:
    driver: bridge
    