apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: devsecops
type: Opaque
stringData:
  POSTGRES_USER: devsecops
  POSTGRES_PASSWORD: devsecops-local-only
  POSTGRES_DB: devsecops
  DB_USER: devsecops
  DB_PASSWORD: devsecops-local-only